### PR TITLE
Remove CSV export for Sales Grid. Unify dropdown icon change on toggle.

### LINKED ISSUE #105: Sales Grid export to CSV not working as expected.
Due CSV currently not supported for the Pivot Grid, the `Export to CSV` is pretty much useless in this sample so it needs to be removed.
Here's how it is looking at the moment:

Image

I think it should be just a single button in this case and loose the dropdown in general.

### PR DESCRIPTION
**Pull request by skrustev**
Fixes #105 for Angular

### CODE REVIEW

**Review by mddragnev — APPROVED** [review]

File: projects/sales-grid/src/app/sales-grid/sales-grid.component.ts [hunk 1]
```diff
@@ -98,6 +93,9 @@ export class SalesGridComponent {
   @ViewChild(IgxPivotGridComponent, { static: true })
   public pivotGrid!: IgxPivotGridComponent;
 
+  @ViewChild(IgxDropDownComponent, { static: true })
+  public viewDropdown!: IgxDropDownComponent;
```
Comment (dkamburov) [inline projects/sales-grid/src/app/sales-grid/sales-grid.component.ts:97]: Do we need to have this here? I don't see it used inside the sales-grid.component

Comment (dkamburov) [reply projects/sales-grid/src/app/sales-grid/sales-grid.component.ts:97]: @skrustev

**Comment by dkamburov** [comment]
@skrustev please resolve the conflict as well
